dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py test --keepdb
deploy:
  provider: heroku
  app: my-decide
  strategy: git
  api_key:
    secure: 4BLVs8dSRfhsubi6sKimDv8wffzBFjfmBz5ubAKX02LE5jlsgBAsOjZVsDYmcXdlnkPTZexBNQtKKDc7p662h4MugRAO2c/QJEzjcfB9OmSEdOWylf4tjGJZ+sTOfV6H085E9ngLmSolErMEoJaRMnRwBFB08fUk/aGPIZBHcrDZD+2a4JFrlStMM+SAnQ7r2gHVzY4zPsesiJ7J+hjzfOhV0/F5WMdtf8ihFbUxPVgjgd5P8++sqX+V7P5jL32h/sD6fCYqAKjeIbQXTW3H6ehUnErvkOz2z1JRDbGagsbaudO9HDLnsMUb9v8vb6sP0M4wRqA/TWFSbNFD3wbiVZmhfkdl5lc/vDNHtjCCHdFhsXQ/vv03k/9lZTnRBqRm0AnlK+nBpe2WAHJpA+ss9tTtfWAxhMrg9aANbxyH094p9bg3XXiAVYDerjZFAjjWfV8WDa1Q2S8xeCm9Jo63CcnsZPPJ4f3SAJjUn6pDQmxTcoUpquboczCILXl697fo+R3Oot+mHPDg1IaZesiUoonisy5lfibp5SdrWxu7qnOdKA0XDWuxkn2AcEIr0eXzKv+FMSvTJL2ZaH/hcn+uK8rM/QpiksDYxuaHPiOYCLBdyI/aToxbea0i/aHXuBmO5nmBpoftsgRBIwy69H09pgF8L1s2NdYTNXWMSy3MCa0=
